### DISCUSSION TITLE
Mailrise on the public domain (:465)

### DISCUSSION THREAD

**Discussion by info-path** [YoRyan/mailrise#120] [Q&A]
I can't get mailrise to work on a public domain. I would like to use it as my smtp server from anywhere.

My intention:
```
[user:465] --> [router:465] --> [traefik route :465 to :8025] --> [mailrise:8025]
```

But I can't establish a connection at all.

```
send-mailmessage -from "admin@homelab.local" -to "telegram@mailrise.xyz" -subject "Windows Test" -body "Test message" -smtpserver mailrise.mydomain.com -port 465
or
send-mailmessage -from "admin@homelab.local" -to "telegram@mailrise.xyz" -subject "Windows Test" -body "Test message" -smtpserver mailrise.mydomain.com -port 465 -UseSsl
```

Return error: `net_io_connectionclosed`

Traefik (exposed ports: 80, 443, 465):
```
mailsecure:
  address: ":465"
```
```
tcp:
  routers:
    mailrise-router:
      entryPoints:
        - mailsecure  # entry point :465
      rule: "HostSNI(`mailrise.mydomain.com`)"
      tls:
        certResolver: cloudflare
      service: mailrise-service

services:
  mailrise-service:
    loadBalancer:
      servers:
        - address: "mailrise.local:8025"
```

mailrise.conf:
```
tls:
  mode: off
```
I have defined the certificate according to this guide: https://technotim.live/posts/traefik-3-docker-certificates/

Has anyone solved this?
