### DISCUSSION TITLE
How to connect to Gotify?

### DISCUSSION THREAD

**Discussion by Luzr** [YoRyan/mailrise#121] [Q&A]
Hi,
How do I intergrade Mailrise with gotify? My config is below and I get the error below when trying to send a test message. I thought I can add the URL for gotify in the config and then send my email to the gotify@mailrise.xyz address.

Config:
```
onfigs:
  gotify:
    urls:
      gotify://gotify.domain.com/message?token=LKWEIOVCc65d
```

Error:
```
PS > send-mailmessage -from "admin@homelab.local" -to "gotify@mailrise.xyz" -subject "Windows Test" -body "Test message" -smtpserver mailriseserver.domain.com -port 8025
send-mailmessage : Mailbox unavailable. The server response was: failed to send notification
```
