### DISCUSSION TITLE
How to filter the sender name correctly and use it in the titel_template?

### DISCUSSION THREAD

**Discussion by ZzenlD** [YoRyan/mailrise#132] [General]
Hello everyone,
I would like to forward messages by email and customize the title as follows: `[<sender name>] <title>`

This means I have to filter the sender name from $from. My attempt looks like this:
```yaml
configs:
  <target-here>:
    urls:
      - mailtos://<mail-destination>
    mailrise:
      title_template: "[${from.split('<')[0].strip()}] ${subject}"

smtp:
  hostname: mailrise.my.domain
  auth:
    basic:
      <username>: <password>
``` 

Unfortunately, this does not work. ${subject} is resolved, but the required part is not.

Does anyone have any idea why this might be, or how I can fix it?

**EDIT:** For example, if the sender is `Nextcloud <nextcloud.my.domain>`, the title should be `[Nextcloud] ${subject}`.

Thanks a lot
