### DISCUSSION TITLE
Configuration issues

### DISCUSSION THREAD

**Discussion by FuzzyMistborn** [YoRyan/mailrise#2] [Q&A] [answered]
Trying to get this set up and running into issues.

When I try to run it in Docker, I get the following error in my log (the container fails to start):

```
/usr/local/bin/python: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```
I'm using Docker-Compose, here's what I have:

```
version: "2"
services:
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    volumes:
      - /home/fuzzydocker/mailrise/mailrise.conf:/etc/mailrise.conf
```

When I try via PyPi, I'm able to get it installed/running, but when I try to send a test message I get the following error:
```
WARNING:apprise:Failed to load Apprise configuration from memory://
```

Here is my config:

```
configs:
  gotify:
    urls:
      gotify://my.url.here/TOKEN
```

**Comment by YoRyan** [comment, marked as answer]
I'm not sure why the Docker image isn't working on your system; it works flawlessly on mine.

```
# docker pull yoryan/mailrise:latest
latest: Pulling from yoryan/mailrise
0bc3020d05f1: Pull complete
a110e5871660: Pull complete
83d3c0fa203a: Pull complete
a8fd09c11b02: Pull complete
14feb89c4a52: Pull complete
70752631d778: Pull complete
be0100d82341: Pull complete
055b01fdac49: Pull complete
7e4fe414911b: Pull complete
6e6206721042: Pull complete
76a324977e18: Pull complete
bf9e37610339: Pull complete
Digest: sha256:118aab6d2e4b6efa2daebfd26275e016fbfee50e8fd378da836f4f235bb31e36
Status: Downloaded newer image for yoryan/mailrise:latest
docker.io/yoryan/mailrise:latest
# docker run -it yoryan/mailrise
usage: mailrise [-h] [--version] [-v] [-vv] CONFIG
mailrise: error: argument CONFIG: can't open '/etc/mailrise.conf': [Errno 2] No such file or directory: '/etc/mailrise.conf'
```

This is Docker 20.10.7 on Ubuntu 20.04/amd64. May I ask what platform you're running on? Perhaps it's not x86?

As for your config trouble, according to the Apprise spec the `urls` key should be a list of strings, not a string. So this should work:

```yaml
configs:
  gotify:
    urls:
      - gotify://my.url.here/TOKEN
```

Note the `-` in front of the URL. 🙂

**Reply by FuzzyMistborn** [reply]
> This is Docker 20.10.7 on Ubuntu 20.04/amd64. May I ask what platform you're running on? Perhaps it's not x86?

It's an LXC which may be part of the issue (I'm just testing it out ATM) but other containers run OK.  It's an x86 based server though.  I'll keep playing with Docker when I get the chance.

> urls key should be a list of strings, not a string

D'oh! That got me past the config error.  Now i'm hitting a 401 error on Gotify which is probably an issue on my end.  Thanks!

**Reply by FuzzyMistborn** [reply]
Moved to a different machine and it's working now.  Thank you!

Also if anybody is looking for a docker-compose (it's really easy but some people struggle), here's mine:
```
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    ports:
      - 8025:8025
    volumes:
      - /home/fuzzy/docker/mailrise/mailrise.conf:/etc/mailrise.conf
    restart: always
```
