### DISCUSSION TITLE
Unable to specify port 25

### DISCUSSION THREAD

**Discussion by JBBBB** [YoRyan/mailrise#59] [Q&A] [answered]
I'm confused...  I have a Mailrise container running in Docker from the yoryan/mailrise image.  It connects directly to the LAN with its own IP address through a macvlan bridge, and is configured with a bind mount to /etc/mailrise/mailrise.conf.  Following is a snippet of the mailrise.conf file...

```
configs:
  smtp:
    hostname:
      - mailrise.home
  listen:
    port:
      - 25
  pfsense@mailrise.home:
    urls:
      - pover://asfasdfasdfasdfasdfasdf@asfdasdfasdfasdfasdf
```
This works well using 8025, and still works with 8025 even after specifying port 25 in the config.  However, it won't work when port 25 is used to send the message.  I get the following error...

`Could not send the message to pfsense@mailrise.home -- Error: Failed to connect to mailrise.home:25 [SMTP: Failed to connect socket: Connection refused (code: -1, response: )]  `

Am I specifying the port incorrectly in the config file?  

**EDIT:**  Port 25 works after recreated the container using the default Docker bridge, rather than a macvlan bridge, and publishing container port 8025 to host port 25.  Rather than mailrise.home having a static LAN IP on the LAN and an address record in my DNS server, I now use mailrise.xyz as a DNS alias for the host, and emails are sent to @mailrize.xyz.  The simplified config is now...

```
configs:
  pfsense:
    urls:
      - pover://asfasdfasdfasdfasdfasdf@asfdasdfasdfasdfasdf
```

I prefer the first method.  Is there any way for the listen.port option to work?  It doesn't appear to have any affect using the yoryan/mailrise image

**Comment by YoRyan** [comment, marked as answer]
YAML doesn't require you to prefix everything with `-`; that particular token means you're inserting a **list**, which is not what you wanted. Here is the corrected version of your original config:

```yaml
configs:
  smtp:
    hostname: mailrise.home
  listen:
    port: 25
  pfsense@mailrise.home:
    urls:
      - pover://asfasdfasdfasdfasdfasdf@asfdasdfasdfasdfasdf
```

As always, you can run your YAML through the [Online YAML Parser](https://yaml-online-parser.appspot.com/) to get a sense of the underlying JSON structure. Try out both versions of the config to see what changes. 👍

**Reply by JBBBB** [reply]
Thank you for the reply and YAML advice, but it still is failing.  I get the same error.

Following is my Docker run command for Mailrise running through a macvlan bridge ...

```
docker run -d \
  --name=mailrise \
  --network=lan2 \
  --hostname=mailrise \
  --ip=192.168.2.213 \
  --dns=192.168.1.1 \
  --dns-search=home \
  --mount type=bind,src=/etc/mailrise/mailrise.conf,dst=/etc/mailrise.conf \
  --restart unless-stopped \
  yoryan/mailrise:latest
```
The mailrise.conf is exactly as you suggest above.

Following are nmap results for three scenarios...

1. Mailrise running on the default Docker bridge with container port 8025 published to host port 25.

```
joe@hub:~$ nmap -p25,8025 mailrise.xyz
Starting Nmap 7.80 ( https://nmap.org ) at 2023-02-23 21:11 EST
Nmap scan report for mailrise.xyz (192.168.1.50)
Host is up (0.00078s latency).
rDNS record for 192.168.1.50: nas.home

PORT     STATE  SERVICE
25/tcp   open   smtp
8025/tcp closed ca-audit-da
```
2. Mailrise running through a macvlan bridge and connected directly to the LAN with its own IP address.

```
joe@hub:~$ nmap -p25,8025 mailrise.home
Starting Nmap 7.80 ( https://nmap.org ) at 2023-02-23 21:11 EST
Nmap scan report for mailrise.home (192.168.2.213)
Host is up (0.00098s latency).

PORT     STATE  SERVICE
25/tcp   closed smtp
8025/tcp open   ca-audit-da
```
3. Healthchecks (_with an integrated SMTP MTA_) running on the same macvlan bridge and connected directly to the LAN with its own IP address.

```
joe@hub:~$ nmap -p25,8025 checks.home
Starting Nmap 7.80 ( https://nmap.org ) at 2023-02-23 21:11 EST
Nmap scan report for checks.home (192.168.2.214)
Host is up (0.00073s latency).

PORT     STATE  SERVICE
25/tcp   open   smtp
8025/tcp closed ca-audit-da
```

The server has two Ethernet interfaces.  One at 192.168.1.50 is for the host OS, minimal Debian 11. The second is configured with three sub-interfaces on macvlan bridges, each on a separate subnet.  My LAN has five subnets.

Nmap results show port 25 is open on the Healthchecks server (checks.home) and closed on mailrise.home, even though both are on the same sub-interface, but with different IPs.  The results also show that port 8025 is still open on mailrise.home even though the server is configured to listen on port 25.

None of the other 10 containers running across the three macvlan bridges using a number of different ports has any problems.  The only conclusion I can draw is that the SMTP MTA in Mailrise is ignoring the configured port.

For what it's worth, I really respect the work you have done on Mailrise and appreciate the effort.  I built and have been using a solution similar to your **SMTP Translator** for several years.   My solution is Exim4 (_running on a repurposed thin client_), which forwards emails to a Python script that then parses them and sends messages to Pushover.   Your solution is a lot more elegant.

**Reply by YoRyan** [reply]
After taking a second look I can see that the hostname and port keys are in the wrong location; they go under the root node, not the `configs` node. Please try this version:

```yaml
smtp:
  hostname: mailrise.home
listen:
  port: 25
configs:
  pfsense@mailrise.home:
    urls:
      - pover://asfasdfasdfasdfasdfasdf@asfdasdfasdfasdfasdf
```
