### DISCUSSION TITLE
Slack custom icon

### DISCUSSION THREAD

**Discussion by winromulus** [YoRyan/mailrise#99] [Q&A]
Hi,

First of all, thank you for the excellent project!

Question: Is there a way to customize the slack icon for the notifications received? It would be great to be able to set custom icons (via image URL or otherwise) to more easily identify the systems that sent the notifications

Thank you!

**Comment by YoRyan** [comment]
I'm not familiar with the Slack plugin, so this is just my reading of the code, but it looks like it attaches the icon from the current [AppriseAsset object](https://github.com/caronc/apprise/wiki/Development_API#the-apprise-asset-object), which for Mailrise is the Mailrise logo.

You can try defining your own asset in your YAML config:
```yaml
configs:
  slacking_off@mailrise.xyz:
    asset:
      app_id: NuxRef
      app_desc: NuxRef Notification
      app_url: http://nuxref.com
      image_url_mask: https://github.com/caronc/apprise/raw/master/apprise/assets/themes/{THEME}/apprise-{TYPE}-{XY}{EXTENSION} 
    urls:
      - slack://[...]
```
