### ISSUE TITLE
SMTP `AUTH LOGIN` no response after inputting the username and password

### ISSUE THREAD

**Issue by dretechtips** [YoRyan/mailrise#101]
Hi there,

My MailRise instance is not providing any response after authenticating. Usually it would provide a response code of 235 if the authentication was successful. Or 535 response code if the authentication data was incorrect. But my instance does not provide any response after entering the base64 encoded username and password. I'm not exactly sure if this is a bug with the MailRise software or an issue with my configuration.

DEMO
```
root@shell-demo:/# telnet [domain_name] 587
Trying 10.42.1.22...
Connected to [domain_name].
Escape character is '^]'.
220 [domain_name] Mailrise 1.3.0
EHLO [domain_name]
250-[domain_name]
250-SIZE 33554432
250-8BITMIME
250-SMTPUTF8
250-AUTH LOGIN PLAIN
250 HELP
AUTH LOGIN
334 VXNlciBOYW1lAA==
dXNlcm5hbWUK
334 UGFzc3dvcmQA
cGFzc3dvcmQK
[No Response]
```

LOGS
```
/home/mailrise/.local/lib/python3.11/site-packages/aiosmtpd/smtp.py:372: UserWarning: Requiring AUTH while not requiring TLS can lead to security vulnerabilities!
  warn("Requiring AUTH while not requiring TLS "
[2024-01-18 20:34:55] WARNING:mail.log:auth_required == True but auth_require_tls == False
[2024-01-18 20:40:16] WARNING:mail.log:auth_required == True but auth_require_tls == False
```

mailrise.conf
```
mailrise.conf: |
    configs:
      basic_assistant:
        urls:
          - hasio://HOST/ACCESS_TOKEN
    # figure out how to map roles directly to user email address
    #import_code: /script/router.py
    listen:
      port: 587
    tls:
      mode: "off"
      #mode: starttls
      #certfile: /etc/ssl/tls.crt
      #keyfile: /etc/ssl/tls.key
    smtp:
      auth:
        basic:
          username: password
      hostname: push.shomenetwork.com
```

For your reference, I am using MailRise 1.3.0 in a Kubernetes container. I've also tried it on the stable edition and I am getting the same issue. I tried it on the latest edition and it seems to be getting a different bug found in issue #98. Could you check if this is a bug with the software?

Thank you,

Andre S.
