### ISSUE TITLE
SMTP Basic authentication not working?

### ISSUE THREAD

**Issue by radhakrisri** [YoRyan/mailrise#102]
My mailrise config is thus:

```
configs:
  # You can send to this config with "telegram@mailrise.xyz".
  #
  telegram:
    urls:
      - tgram://<mytgramtoken>/mychatid/
    # You can also control the layout of the message with custom template
    # strings.
    # mailrise:
    #   title_template: "Urgent: ${body}"
    #   body_template: ""
    #   body_format: text
  pover:
    urls:
      - pover://<mypushoverid>
smtp:
  auth:
    basic:
      myusername:mypassword
```

As you can see, I have smtp auth specified above. However, the following command works, even when no authentication details are passed in. 

```
sendemail -f someone@somewhere.com -t telegram@mailrise.xyz -u "Test Email 2" -m "Hello World!" -s 192.168.x.x:8025
```

Any idea what's going on? How can I verify smtp authentication is working as expected?

Radha.
