### ISSUE TITLE
pushover.failure sends notification, but doesn't alert message severity level

### ISSUE THREAD

**Issue by c3101** [YoRyan/mailrise#12]
I'd expect it to come through to pushover with a different severity level to distinguish it from other, less important, messages

**Comment by YoRyan** [comment]
So it turns out this is a quirk with the way that Apprise works with Pushover. Debugging Mailrise shows that the `.failure` notification type is being submitted to the [Apprise API](https://github.com/caronc/apprise/wiki/Development_API#message-types-and-themes) correctly, which is supposed to give you a red Mailrise icon for that notification—except that Apprise's Pushover plugin [does not do anything useful](https://github.com/caronc/apprise/blob/master/apprise/plugins/NotifyPushover.py#L305) with the `notify_type` passed to it. This actually makes sense, because Pushover notifications cannot set their own icons; icons are defined on a per-app basis on the Pushover dashboard.

You're probably looking for Pushover's "priority" option, which you [add to the query string of the service URL](https://github.com/caronc/apprise/wiki/Notify_pushover). You have a choice of `low`, `moderate`, `high`, or `emergency`:

```yaml
configs:
  pushover:
    urls:
      - pover://pover://{user_key}@{token}?priority=low
  pushover_urgent:
    urls:
      - pover://pover://{user_key}@{token}?priority=emergency
```
