### ISSUE TITLE
ntfys (and maybe other) not working in docker with self signed certificate

### ISSUE THREAD

**Issue by AlBundy33** [YoRyan/mailrise#126]
docker-compose.yml
```
services:
  mailrise:
    image: yoryan/mailrise
    restart: unless-stopped
    volumes:
      - ./mailrise.conf:/etc/mailrise.conf:ro
      - /etc/ssl/certs/MyRootCA.pem:/etc/ssl/certs/MyRootCA.pem:ro
      - /etc/ssl/certs/afe69bea.0:/etc/ssl/certs/afe69bea.0:ro
      - /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt:/etc/ssl/certs/ca-certificates.crt:ro
    ports:
      - 8025:8025
```
mailrise.conf
```
configs:
  ntfy:
    urls:
      - ntfys://ntfy.my.domain/test
```
inside the mailrise container I can curl https://ntfy.my.domain/test but I get an error if I try to send a mail with
```
swaks --to ntfy@mailrise.xyz --server localhost:8025
```

```
mailrise-1  | [2024-07-28 00:04:28] WARNING:apprise:A Connection error occurred sending ntfy:https://ntfy.my.domain notification.
mailrise-1  | [2024-07-28 00:04:28] WARNING:mailrise.skeleton:Notification failed: address: [ root@2ff14d9b3ee2 ➤ ntfy@mailrise.xyz ] subject: [ test Sun, 28 Jul 2024 00:04:27 +0000 ] body: [ This is a test maili (0.0K) ]
```

it seems that python is not using /etc/ssl/certs by default
https://stackoverflow.com/questions/70855939/python-requests-not-looking-into-etc-ssl-certs-for-self-signed-certificates

Calling ntfy over http works but I would prefer https

solution: https://github.com/YoRyan/mailrise/issues/126#issuecomment-2254600941
