### ISSUE TITLE
CRITICAL:mailrise.skeleton:Invalid config key '%s'; should be a string or an email address without periods in the username

### ISSUE THREAD

**Issue by nzbtuxnews** [YoRyan/mailrise#141]
I've got Mailrise setup and working fine for all recipients except one that has periods in its username (see 2nd recipient in example below)..
```
configs:
  something@somedomain.com:
    urls:
      - mailto://<someting>:<somepassword>@somedomain.com
  some.ting.1@someotherdomain.com:
    urls:
      - mailto://<some.ting.1>:<somepassword>@someotherdomain.com
```

Mailrise logs show:

`[2025-02-12 22:42:17] CRITICAL:mailrise.skeleton:Invalid config key '%s'; should be a string or an email address without periods in the username`

If I remove the periods in "some.ting.1" it works perfectly.

The Wiki is not showing how to deal with this. I tried putting the email in quotes but still complains...
