### ISSUE TITLE
Silent Failure: No Logs, SMTP Connection Refused in yoryan/mailrise:latest

### ISSUE THREAD

**Issue by chancellor1101** [YoRyan/mailrise#146]
I’m experiencing a silent failure with Mailrise. The container starts but:

- Produces no logs (even with `LOG_LEVEL=debug`)
- Refuses SMTP connections both locally and from other machines  
- Appears "Up" (`docker ps`) and port 1025 is bound, but:
  - `telnet localhost 1025` connects briefly then closes
  - `telnet <host-ip> 1025` returns `Connection refused`

I suspect a bug in the `yoryan/mailrise:latest` image or a dependency issue (e.g., Apprise crash).

---

## Environment

- **Mailrise Version:** `yoryan/mailrise:latest` (also tested `0.3.0`)
- **Docker Version:** `28.2.2, build e6534b4`
- **Host OS:** Debian 12 Bookworm (Proxmox LXC)
- **Python Version (in container):** Python 3.12.1
- **Network Setup:** Docker container VM; client IP: `10.10.0.17`

---

## Steps to Reproduce

1. **docker-compose.yml**

   ```yaml
   version: '3'
   services:
     mailrise:
       image: yoryan/mailrise:latest
       container_name: mailrise
       ports:
         - "0.0.0.0:1025:1025"
       volumes:
         - /opt/arr-configs/mailrise/mailrise.conf:/etc/mailrise.conf:ro
       environment:
         - LOG_LEVEL=debug
       restart: unless-stopped
   ```

2. **/opt/arr-configs/mailrise/mailrise.conf**

   ```yaml
   configs:
     sonarr@localhost:
       urls:
         - json://http://home.--.family/api/webhook/--
     pve@localhost:
       urls:
         - json://http://home.--.family/api/webhook/--
     watchtower@localhost:
       urls:
         - json://http://home.--.family/api/webhook/--
     "*@*":
       urls:
         - json://http://home.--.family/api/webhook/--
   ```

3. Start the container:

   ```bash
   docker-compose up -d
   ```

4. Check logs:

   ```bash
   docker logs mailrise
   # No output
   ```

5. Test SMTP connections:

   ```bash
   telnet localhost 1025
   # Connects briefly, then "Connection closed by foreign host"

   telnet 10.10.0.17 1025
   # Connection refused
   ```

6. Confirm port is bound:

   ```bash
   sudo netstat -tulnp | grep 1025
   # tcp 0 0 0.0.0.0:1025 0.0.0.0:* LISTEN 199522/docker-proxy
   ```

---

## Expected Behavior

- Mailrise should log startup details (especially with `LOG_LEVEL=debug`)
- Accept SMTP connections on port 1025 from local and remote IPs
- Deliver emails to appropriate Apprise webhook targets

---

## Actual Behavior

- No logs produced (`docker logs mailrise` is empty)
- SMTP port bound but connections are dropped/refused
- Container status is `Up`, but does not function

---

## Troubleshooting Attempted

- ✅ Validated config with:

  ```bash
  docker exec -it mailrise python -c "import yaml; yaml.safe_load(open('/etc/mailrise.conf'))"
  ```

- ✅ Verified file is mounted:

  ```bash
  docker exec -it mailrise cat /etc/mailrise.conf
  ```

- ✅ Enabled `LOG_LEVEL=debug` (no effect)

- ✅ Re-pulled latest image

- ⛔ Cannot inspect processes (`ps` missing in Alpine)

- ✅ Confirmed Python version: 3.12.1

- ✅ No host firewall (ufw/iptables not blocking)

- 🔍 DNS resolution not confirmed due to lack of `curl`/`ping`

- ❓ Potential Apprise issue—forums mention 1.1 problems—but cannot test in current image

---

## Suspected Cause

- Bug or crash in `yoryan/mailrise:latest` during init (no logs, silent fail)
- Apprise dependency failure (e.g., with Python 3.12.1)
- Entrypoint (`mailrise`) may fail without raising visible errors

---

## Request

Could you help identify why Mailrise is silently failing with no logs and broken SMTP binding?

- Are there known issues with `latest` or Python 3.12.1?
- Any suggestions for debugging or workaround (e.g., custom image with upgraded Apprise)?
- Should I pivot to using Postfix or Apprise’s own SMTP server?

---

## Relevant Logs and Outputs

- `docker logs mailrise`: *(empty)*
- `netstat` output:

  ```
  tcp 0 0 0.0.0.0:1025 0.0.0.0:* LISTEN 199522/docker-proxy
  ```

- `docker inspect` (excerpt):

  - `State.Status`: `running`
  - `Cmd`: `["/etc/mailrise.conf"]`
  - `Entrypoint`: `["mailrise"]`
  - `Env`: includes `LOG_LEVEL=debug`, `PYTHON_VERSION=3.12.1`

---

Let me know if a minimal test image or reproduction case would help further. Thanks!
