### ISSUE TITLE
Failed to send to Discord notification: Bad Request

### ISSUE THREAD

**Issue by samcro1967** [YoRyan/mailrise#16]
I have 9 cron jobs setup that send an email to mailrise which in turns sends them to Gotify and Discord.  All 9 work to Gotify. 2 of 9 work to Discord.  Below is the error message I see in the logs, [error=400](https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1).

Is this something within mailrise or is it something I need to log an issue with apprise?

```
[2022-05-14 09:00:05] WARNING:apprise:Failed to send to Discord notification: Bad Request - Unsupported Parameters., error=400.
[2022-05-14 09:00:05] WARNING:mailrise.skeleton:Notification failed: Cron <local@local4> bash /home/osuhickeys/Documents/Docker/gitea/gitea_backup.sh ➤ cron@local.net
```

**Comment by kaitallaoua** [comment]
I have the same issue, emails coming from proxmox backups to discord are failing. I already sent a test email of just text so it does work.
```
[2023-07-02 15:54:33] WARNING:apprise:Failed to send to Discord notification: Bad Request - Unsupported Parameters., error=400.
[2023-07-02 15:54:33] WARNING:mailrise.skeleton:Notification failed: vzdump backup status (pve-general-rig.localdomain) : backup successful ➤ pve_general_rig_discord.warning@mailrise.xyz
```

I tried text and html and markdown
```
configs:
 pve_general_rig_discord:
  mailrise:
   body_format: html
  urls:
   - https://discord.com/api/webhooks/........./............
```

```
version: "2.1"
services:
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    restart: unless-stopped
    ports:
      - 8025:8025
    volumes:
    - ./mailrise.conf:/etc/mailrise.conf:ro
```

I don't have a handy way to get the email, but it should look like the following:
https://www.servethehome.com/wp-content/uploads/2022/12/Proxmox-VE-Backup-Successful-e-mail.jpg

or the other kinds like shown in the blog (the dark mode photos): https://www.servethehome.com/proxmox-ve-e-mail-notifications-are-important/

**Comment by YoRyan** [comment]
These emails contain entire logs. So I think what's happening here is that Discord is rejecting them for exceeding the maximum length. It's like copy-pasting a log file into the Discord app; you're going to get rejected.

You can cut split your messages into multiple notifications using Apprise's [overflow options](https://github.com/caronc/apprise/wiki/URLBasics#global-parameter-breakdown), but beware that they can be defeated by a long subject line, which isn't currently included in the split calculation (https://github.com/caronc/apprise/issues/845).

For future reference, you should be able to retrieve the message by turning on debug logging (`-vvv`):

```yaml
version: "2.1"
services:
  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    restart: unless-stopped
    ports:
      - 8025:8025
    volumes:
      - ./mailrise.conf:/etc/mailrise.conf:ro
    command: -vvv /etc/mailrise.conf
```
