### ISSUE TITLE
No module named 'mailrise'

### ISSUE THREAD

**Issue by Maltretiert** [YoRyan/mailrise#24]
Hello, I got an issue where the log would tell me

```
Traceback (most recent call last):

  File "/home/mailrise/.local/bin/mailrise", line 5, in <module>

    from mailrise.skeleton import run

ModuleNotFoundError: No module named 'mailrise'
```

All I did was trying to run it from docker compose with the following docker-compose.yml

version: "3"

```
services:
  mailrise:
    image: yoryan/mailrise:latest
    ports:
      - 24:25
    user: "root"
    environment:
      - TZ="Europe/Berlin"
    restart: unless-stopped
    volumes:
      - /opt/mailrise/data/mailrise.conf:/etc/mailrise.conf:ro

```

my mailrise.conf looks like this even though I dont think it matters much in this case

```
configs:
  gotify:
    urls:
      - gotify://IP/Token

```

As you probably already guessed Im quite new to this so help would be great :)

**Comment by YoRyan** [comment]
Your compose.yml doesn't work due to the presence of these lines:
```yaml
ports:
  - 24:25
user: "root"
```
If you refer to the base [Dockerfile](https://github.com/YoRyan/mailrise/blob/main/Dockerfile), you'll see that the internally exposed port is 8025, not 25, and that the container is designed to run as the `mailrise` non-root user rather than as `root`.

So you want:
```yaml
ports:
  - 24:8025
# no need for a user: line
```
Hope this helps!
