### ISSUE TITLE
Unable to start docker container

### ISSUE THREAD

**Issue by PierreDurrr** [YoRyan/mailrise#26]
I should have made some configuration mistake, but can't see where...
All i got is in my container is 

```
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) unrecognised: GET
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) unrecognised: HOST:
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) unrecognised: USER-AGENT:
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) unrecognised: ACCEPT:
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) unrecognised: ACCEPT-LANGUAGE:
24/11/2022 14:57:35 [2022-11-24 13:57:35] WARNING:mail.log:('10.0.0.210', 55783) too many bogus commands
```

Here is my docker-compose :

```yaml
mailrise:
  image: yoryan/mailrise:latest
  container_name: mailrise
  ports:
    - 8025:8025
  volumes:
    - /docker_data2/mailrise/config/mailrise.conf:/etc/mailrise.conf
  restart: unless-stopped
  labels:
    - "com.centurylinklabs.watchtower.enable=true"
```

and here is my config file :

```yaml
configs:
  discord@mailrise.xyz:
    urls:
      - discord://REDACTED/REDACTED
```
