### ISSUE TITLE
Advertise auth support in EHLO

### ISSUE THREAD

**Issue by bt90** [YoRyan/mailrise#38]
I'm basically hitting the problem described here:

https://marlam.de/msmtp/old-mailinglist/msg00533.html

I've configured mailrise to use basic authentication but msmtp fails to send mails.

EHLO as reported by `msmtp -v`:

```
<-- 220 a4360929b762 Mailrise 0.0.post1.dev1+gbf98187
--> EHLO localhost
<-- 250-a4360929b762
<-- 250-SIZE 33554432
<-- 250-8BITMIME
<-- 250-SMTPUTF8
<-- 250 HELP
--> QUIT
<-- 221 Bye
msmtp: the server does not support authentication
msmtp: could not send mail (account mailrise from /etc/msmtprc)
```

According to the msmtp devs the mailserver should report this as part of its EHLO.

Btw the Readme is a bit confusing. The example seems to be missing the `auth` key.

Readme:

```yml
smtp:
  basic:
    username: password
    AzureDiamond: hunter2
```

Correct config according to https://github.com/YoRyan/mailrise#configuration

```yml
smtp:
  auth:
    basic:
      username: password
```

**Comment by bt90** [comment]
Redacted version of my current configuration:

```yml
configs:
  pushover:
    urls:
      - pover://xxxxxxxxxxxxx@yyyyyyyyyyyyyyyyyyy
smtp:
  auth:
    basic:
      pushover: xxxxxxxxxxxxx
```

But apparently authentication doesn't seem to enforced at all?

```sh
curl smtp://localhost:8025 --mail-rcpt pushover@mailrise.xyz -T - <<<"Test E-Mail"
```

This triggers a Pushbullet notification even if no credentials are provided.
