### ISSUE TITLE
Session.login_data is deprecated

### ISSUE THREAD

**Issue by bt90** [YoRyan/mailrise#39]
Looks like a warning generated by [aiosmtpd](https://github.com/aio-libs/aiosmtpd/blob/330e9efd6e045c2a84bb243bb446e44c2eb4e266/aiosmtpd/smtp.py#L180-L185):

```
WARNING:mail.log:Session.login_data is deprecated and will be removed in version 2.0
```

**Comment by YoRyan** [comment]
Can you provide a sample configuration file? It looks to be an upstream bug in aiosmtpd, because Mailrise doesn't touch `login_data` anywhere.

**Comment by bt90** [comment]
```yml
configs:
  pushover:
    urls:
      - pover://xxxxxxxxxxxxxxxx@yyyyyyyyyyyyyyyyy
smtp:
  auth:
    basic:
      pushover: xxxxxxxxxxxxxxxxxxx
```
