### ISSUE TITLE
Allow environment variable configuration to be passed to configuration file

### ISSUE THREAD

**Issue by onedr0p** [YoRyan/mailrise#42]
Hi 👋🏼 it would be nice if the configuration file could read env vars, home assistant has a [pretty neat way](https://www.home-assistant.io/docs/configuration/yaml/#environment-variables) for this to work

## docker compose

```yaml
mailrise:
  image: yoryan/mailrise
  container_name: mailrise
  restart: unless-stopped
  env:
    DISCORD_WEBHOOK: discord://WEBHOOK_ID/WEBHOOK_TOKEN
  volumes:
    - ./mailrise.conf:/etc/mailrise.conf:ro
```

## mailrise config

```yaml
configs:
  telegram_and_discord:
    urls:
      - !env_var DISCORD_WEBHOOK
```

This feature is pretty handy when using an orchestration platform like Kubernetes where you can use secrets as environment variables.
