### ISSUE TITLE
Allow use of variables in urls

### ISSUE THREAD

**Issue by Efocat** [YoRyan/mailrise#49]
It would be nice to expand the use of template string variables in urls for a catch all config

for example:

```yaml
configs:
  # gmail pass-through
  "*@gmail.com":
    urls:
      - mailtos://user:password@gmail.com?from=${from}&to=${to}
    mailrise:
      title_template: "${subject}"
```

essentially this enables mailrise the ability to easily pass-through email to an external smtp server with a catch all

my use case is for [Ombi](https://github.com/Ombi-app/Ombi) where the system may send notification to multiple users using mailrise but some user only has email configured and it would be tedious to have individual entry for each of those user.

Version 1.3.0
