### ISSUE TITLE
Unable to get container working

### ISSUE THREAD

**Issue by sdooweloc** [YoRyan/mailrise#52]
Hey all. I am at a loss here. Trying to get mailrise working in a container with traefik and cannot for the life of me figure it out.
The container reports as running but has 0 logs when I run `docker logs mailrise`
I tried looking in the container but dont see any place that would define a log file or anything internally.
When I try to send a test email from for example gitea to mailrise.my.domain:465 gitea just hangs and nothing ever comes through. I have provided my configs below if anyone can offer assistance please.

If I have missed a file or something that would be useful for troubleshooting please let me know. I love the concept of this app and want to get it working and will do whatever needed to help that process happen.

Docker-compose.yml
```yml
networks:
  proxy:
    external: true

services:
  mailrise:
    image: yoryan/mailrise
    container_name: mailrise
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /mnt/docker/mailrise/mailrise.conf:/etc/mailrise.conf:ro
    labels:
      traefik.tcp.routers.mailrise.rule: "HostSNI(`*`)"
      traefik.tcp.routers.mailrise.tls: "true"
      traefik.tcp.routers.mailrise.certresolver: "cloudflare"
      traefik.tcp.routers.mailrise.tls.domains[0].main: "mailrise.my.domain"
      traefik.tcp.routers.mailrise.tls.domains[0].sans: ""
      traefik.tcp.routers.mailrise.entrypoints: "mailsecure"
      traefik.docker.network: "proxy"
```

mailrise.conf
```yml
configs:

  crowdsec:
    urls:
      - discord://ID/key    
   

  gitea:
    urls:
      - discord://ID/KEY


smtp:
  auth:
    basic:
      username: password
      AzureDiamond: hunter2
```

traefik.yml
```yml
...
entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
  mailsecure:
    address: ":465"
...
certificatesResolvers:
  cloudflare:
    acme:
      email: myemail 
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
...
```

**Comment by sdooweloc** [comment]
> 

What command are you referring to? The docker compose doesnt include a command in your templates and running it just uses `docker-compose up -d` so I am not sure where you are wanting me to pass the -v and config location.

The proxy network is what everything that is behind traefik is on and no other containers have any issues being on it. I have an entire media stack, gitea, portainer, and more all on that network with IPs and connectivity with my external machine and each other.

**Comment by YoRyan** [comment]
I'm referring to the [command-line arguments passed to the container](https://docs.docker.com/compose/compose-file/#command). In Compose, you set these with the `command` field.
```yaml
services:
  mailrise:
    image: yoryan/mailrise
    container_name: mailrise
    command: -vv /etc/mailrise.conf
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /mnt/docker/mailrise/mailrise.conf:/etc/mailrise.conf:ro
    labels:
      traefik.tcp.routers.mailrise.rule: "HostSNI(`*`)"
      traefik.tcp.routers.mailrise.tls: "true"
      traefik.tcp.routers.mailrise.certresolver: "cloudflare"
      traefik.tcp.routers.mailrise.tls.domains[0].main: "mailrise.my.domain"
      traefik.tcp.routers.mailrise.tls.domains[0].sans: ""
      traefik.tcp.routers.mailrise.entrypoints: "mailsecure"
      traefik.docker.network: "proxy"
```
Also see if you can get any services to reach Mailrise directly (by IP address), without going through Traefik.
