### ISSUE TITLE
SMTP Doesn't work

### ISSUE THREAD

**Issue by cozhelp** [YoRyan/mailrise#94]
I need help getting Mailrise to send emails through Gmail. I can get it to work for Apprise. I'm able to get Mailrise to work for other services like ntfy. I am using the Gmail app password like Apprise specifies.

```
configs:

  "*@*":
    urls:
      - mailto://myuser:myapppassword@gmail.com

tls:
  mode: off

```
